spring:
  # DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.81:3306/xiguazi?yearIsDateType=false
    username: xiguazi
    password: 123456

  # Thymeleaf
  thymeleaf:
    enabled: true
    encoding: UTF-8

  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${resource_path}

  # Upload file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # Elasticsearch
elasticsearch:
  host: 192.168.1.81
  port: 9200

logging:
  level:
    org.springframework.web: trace
    com:
      smoke:
        xiguazi:
          controller: debug
          mapper: debug
          service: debug

# Static resource file path
resource_path: D:/project/ws-graduation-project/static/

